server:
    port: 9001
    servlet:
        context-path: /meesho-categorymicroservice
spring:
    datasource:
        password: 123
        url: jdbc:mysql://localhost:3306/MeeshoApp
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true


    application:
        name: CATEGORY-SERVICE
