server:
    port: 9001
    servlet:
        context-path: /meesho/category-microservice
spring:
    datasource:
        password: 12345678
        url: jdbc:mysql://192.168.1.76:3306/MeeshoApp
        username: meesho
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true


    application:
        name: CATEGORY-SERVICE
